services:
  python-tutor:
    image: python-tutor
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
    tty: true
